
###

GET http://localhost:3000/api/super

###

POST http://localhost:3000/api/super
Content-Type: application/json 

{
    "Nombre" : "Naruto",
    "Años" : "666",
    "IdentidadSecreta" : "Goku",
    "Poderes" : "Evangelizacion"
}

###

GET http://localhost:3000/api/super/641bc5684671e9378da84cce